version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  wordpress:
    depends_on:
      - db
      - ftp
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite

  ftp:
    image: stilliard/pure-ftpd:latest
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    restart: always
    volumes: ['./:/home/example']
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: example
      FTP_USER_PASS: example
      FTP_USER_HOME: /home/example
    networks:
      - wpsite

networks:
  wpsite:

volumes:
  db_data: